# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches: 
    - main
    - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python_version: [3.7, 3.8, 3.9]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        
      # Setup Python
      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2 # Setup Python
        with:
          python-version: ${{ matrix.python_version }}
          architecture: 'x64'
      
      # pip
      #- name: Get pip cache dir
      #  id: pip-cache
      #  run: echo "::set-output name=dir::$(pip cache dir)"
      
      #- name: pip cache
      #  uses: actions/cache@v2
      #  with:
      #    path: ${{ steps.pip-cache.outputs.dir }}
      #    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #    restore-keys: ${{ runner.os }}-pip-
       
      - name: Install requirements with pip
        uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      
      - name: Run unit tests
        run: |
          cd src/
          python -m unittest test_activation_functions.py
          python -m unittest test_losses.py
          python -m unittest test_regularizations.py
          python -m unittest test_weights_inits.py
          python -m unittest test_network.py
        
